spring:
  datasource:
    data: classpath:sql/import_data_h2.sql
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:da;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: user
      password:
      connection-test-query: SELECT 1

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true